### ISSUE TITLE
Show initial setup of game

### ISSUE THREAD

**Issue by snehaparande** [step-8/acquire-poirot#16]
As a player
I want initial game setup
So that I can start playing game

### Acceptance Criteria:

- [x] - [ ] Criteria 1:
  - Given I'm on game page
  - When page is loaded 
  - Then I should see a [game page](https://user-images.githubusercontent.com/99525537/183092591-0214194f-f6f6-4977-84b9-aa371293b402.jpeg) with :- 
      - Empty game board
      - Stock market
      - $6000 in my account
      - Place Holder for logs, players and player stocks

- [ ] Criteria 2:
  - Given I'm on game page and I can see information card button
  - When I click on information card button 
  - Then I should see [information card](https://user-images.githubusercontent.com/99525537/183098471-6ca93f29-1eea-4547-9f0b-8a6711b4da89.jpeg)

**Comment by tanmaysamanta** [comment]
Please remove criteria 3. We can do this later.
